[tool.poetry]
name = "neenee"
version = "0.0.1"
description = "A personal Discord bot, for developers, acting as a robust testbed"
authors = ["HitBlast <hitblastlive@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
disnake = "^2.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
